### ISSUE TITLE
Sourcemaps, CSS-Urls

### ISSUE THREAD

**Issue by fab1an** [dlepaux/fingerprint-brunch#1]
I've written something similar (unpublished), I'm thinking about switching and I have some questions:

1. Does your plugin rename referenced assets in css-urls?
2. If it renames the generated js-files, does it also fix the sourceMap link?
3. If it renames the gerneated css-file, does css-reload work? For me it doesn't because brunch takes the old filename.

Thank you.

**Comment by dlepaux** [comment]
Hello Fabian !

1. Does your plugin rename referenced assets in css-urls?
Currently not, but it's a good idea to implement ! I will think about it...

2. If it renames the generated js-files, does it also fix the sourceMap link?
Exemple : I want to rename this javascript file `master.js`.
Brunch will make the source map normally with started file name (`master.js.map`) and put something like this to the end of compiled file `//# sourceMappingURL=master.js.map`. After this i rename the file to `master-sc45cs.js`. The source map file name doesn't need to be renamed. (I hope you will understand me)

3. If it renames the gerneated css-file, does css-reload work? For me it doesn't because brunch takes the old filename.
Yes it doesn't work... But i don't know how to fix it.

Cheers

**Comment by dlepaux** [comment]
Fabian,

I have an idea for the 3. point. Hashing of asset is usefull only in prod right ? So if i detect the prod environment i hash assets else no. 

What do you think about this ?

Thank you

**Comment by fab1an** [comment]
Seems like a good idea. I have published my module here: https://github.com/fab1an/hash-brunch

It also writes of image-sizes into the manifest and it hashing works incrementally (though the algorithm might be not stable, because it relies on file-names).

**Comment by dlepaux** [comment]
Thank you for sharing ! :)

**Comment by dlepaux** [comment]
Hi @fab1an,

I have just done your todo list ! :)
I will write a little documentation soon, enjoy
