### ISSUE TITLE
Digest not generated at all

### ISSUE THREAD

**Issue by Spazer9** [dlepaux/fingerprint-brunch#13]
I could not get the plugin to work at all. I even downloaded the "examples" folder and ran `brunch build` and it just compiled the regular files with no digests/hashes in the file names.

![](https://s3.amazonaws.com/snaps-bucket/2017/09/YZDg1Ae/2017-09-26_03-25-47.png)

I'm on Brunch 2.10.10 and Node v8.3.0 and Windows 10

Any idea?

**Comment by dlepaux** [comment]
Hello @Spazer9 ,

It seem to be an issue with node-sass and windows.

First, could you try to do an `npm install` instead of `yarn` to see error logs, I got an Exit status 1 with node version `8.5.0`. If you have no error, could you run `npm test` on the root and show me output ?

If you have a node-sass error, I suggest you to downgrade to the [NodeJS LTS version 6.11.3](https://nodejs.org/dist/v6.11.3/node-v6.11.3-x64.msi).
